export const site = {
  name: "Lone Star Total Wash",
  url: "https://www.lonestartotalwash.com",
  phoneDisplay: "(903) 431-8489",
  phoneHref: "+19034318489",
  facebook: "https://www.facebook.com/profile.php?id=61584723370422",
  tiktok: "https://www.tiktok.com/@lonestartotalwash",
  locality: "Hallsville",
  region: "TX",
  postalCode: "75650",
  areas: ["Hallsville", "Longview", "Marshall", "Kilgore", "Tyler", "East Texas"],
};

export const services = [
  {
    slug: "fleet-washing",
    eyebrow: "Keep equipment moving",
    title: "Mobile Fleet Washing",
    short: "Semis, trailers, service trucks, buses, vans, tankers, and multi-unit commercial fleets.",
    hero: "/images/jobs/tx-27.jpg",
    alt: "Clean Mack day cab and belly dump trailer after a mobile fleet wash",
    points: [
      "On-site service reduces driver detours and lost route time",
      "One-time cleans and recurring fleet schedules",
      "After-hours and weekend scheduling when available",
      "Written scope before work begins",
    ],
    intro: "A fleet does not make money sitting in a wash line. Lone Star Total Wash brings the wash to your yard, route base, or job site and plans the work around your operating window.",
    who: "Trucking companies, contractors, delivery fleets, shuttle operators, service companies, municipalities, and owner-operators across East Texas.",
    faq: [
      ["Do drivers have to take trucks out of service?", "The goal is to wash parked equipment at your location and during a window that protects route time. The exact sequence is confirmed during the quote."],
      ["Can you price a recurring schedule?", "Yes. Ask for weekly, monthly, quarterly, or seasonal options. Frequency depends on equipment use, site conditions, and the finish you need."],
      ["Do you wash trailers and tankers?", "Yes. Published base rates cover common truck and trailer types, including a separate option for aluminum brightener on tankers."],
    ],
  },
  {
    slug: "heavy-equipment-washing",
    eyebrow: "Mud, grease, and job-site buildup",
    title: "Heavy Equipment Washing",
    short: "Excavators, skid steers, dump trucks, oilfield equipment, and construction machinery.",
    hero: "/images/jobs/tx-30.jpg",
    alt: "John Deere excavator cleaned by Lone Star Total Wash",
    points: [
      "Mobile cleaning at the yard or approved job site",
      "Hourly base pricing for equipment of any size",
      "Walkaround and access plan before work starts",
      "Photos of completed work available on request",
    ],
    intro: "Heavy equipment carries the job site home with it. A planned wash makes inspections, maintenance, transport, and company presentation easier without sending machinery across town.",
    who: "Excavation crews, oilfield operators, land-clearing companies, concrete contractors, utilities, rental yards, and equipment owners.",
    faq: [
      ["How is heavy equipment priced?", "The published base rate is $137.50 per hour. The estimate confirms access, buildup, machine size, travel, water, and any site-specific requirements before work starts."],
      ["Can equipment be washed on an active job site?", "Sometimes. The site must have safe access and an approved wash area. Tell us about the surface, drainage, utilities, and operating schedule when requesting a quote."],
      ["What should be ready before the wash?", "Park the machine in the agreed location, remove personal items, identify sensitive components, and make sure the operator or site contact is reachable."],
    ],
  },
  {
    slug: "commercial-pressure-washing",
    eyebrow: "A cleaner first impression",
    title: "Commercial Pressure Washing",
    short: "Storefronts, sidewalks, parking areas, drive-throughs, dumpster pads, and building exteriors.",
    hero: "/images/jobs/tx-14.jpg",
    alt: "East Texas office storefront and walkway after pressure washing",
    points: [
      "Service planned around customers and operating hours",
      "One-time cleanup or written recurring schedule",
      "Square-foot base pricing for larger flat-work jobs",
      "Clear scope for entrances, concrete, walls, and high-soil areas",
    ],
    intro: "Customers see the concrete, entrance, and storefront before they see anything inside. Lone Star Total Wash handles the high-traffic exterior areas that collect dirt, organic buildup, oil, and everyday grime.",
    who: "Retailers, restaurants, offices, warehouses, churches, schools, property managers, and commercial site operators.",
    faq: [
      ["Can the work happen after closing?", "After-hours and weekend scheduling may be available. The estimate identifies access, lighting, noise, water, and reopening time before a date is set."],
      ["Do you offer recurring property service?", "Yes. Published recurring base rates are available with a signed service agreement for monthly, quarterly, or semiannual work."],
      ["Can you quote multiple exterior areas together?", "Yes. List the entrances, sidewalks, parking stalls, walls, dumpster areas, and drive-through surfaces you want reviewed."],
    ],
  },
  {
    slug: "residential-pressure-washing",
    eyebrow: "Clear the buildup without the guesswork",
    title: "Residential Pressure Washing",
    short: "Driveways, patios, walkways, porches, brick, home exteriors, and roof-wash estimates.",
    hero: "/images/jobs/tx-18.jpg",
    alt: "Residential driveway before and after pressure washing",
    points: [
      "Free on-site quote with no obligation",
      "Service matched to the surface and condition",
      "Driveways, patios, walkways, porches, brick, and exteriors",
      "Direct scheduling with Travis",
    ],
    intro: "East Texas humidity and shade can leave concrete, brick, and exterior surfaces looking older than they are. A site visit determines the surface, buildup, access, and right cleaning plan before a price is given.",
    who: "Homeowners, landlords, property managers, real-estate sellers, and families preparing for a gathering or seasonal cleanup.",
    faq: [
      ["Can every surface be cleaned the same way?", "No. Surface material, age, coatings, drainage, and the type of buildup matter. The quote should identify the method appropriate for the actual surface."],
      ["Do I need to be home?", "That depends on access, water, pets, gates, and the scope. Travis will confirm the plan before scheduling."],
      ["Do you provide roof-wash estimates?", "Yes. Send the property location and describe the roof and visible buildup. The site must be reviewed before work is accepted."],
    ],
  },
];

export const areaLandingPages = [
  {
    slug: "hallsville-tx",
    name: "Hallsville",
    image: "/images/jobs/tx-27.jpg",
    description: "Hallsville mobile fleet and pressure washing for trucks, equipment, commercial property, concrete, and homes. See real work and get a free quote.",
    lead: "Lone Star Total Wash is based in Hallsville and brings mobile washing to local yards, job sites, businesses, and homes. The goal is simple: confirm the real scope, show the base pricing, and give you a direct next step with Travis.",
    planning: "Hallsville is the home base, but every job still starts with the address and work area. Access, equipment count, surface condition, water, drainage, and the requested service window determine what belongs in the written estimate.",
    focus: "Local fleet and property work without the runaround",
    audiences: ["Commercial trucks, trailers, and service vehicles", "Excavators, skid steers, dump trucks, and job-site equipment", "Storefronts, concrete, walkways, and exterior work areas", "Driveways, patios, brick, and residential exteriors"],
    faq: [
      ["Is Lone Star Total Wash based in Hallsville?", "Yes. Lone Star Total Wash is Hallsville-based and provides mobile washing for approved commercial, fleet, equipment, and residential jobs across East Texas."],
      ["Can I get a Hallsville quote without knowing the square footage?", "Yes. Send the address, photos, and a plain description of the area or equipment. Travis will tell you what can be priced from those details and what needs an on-site look."],
      ["Do you offer recurring Hallsville fleet or property washing?", "Recurring schedules may be available. The written quote confirms the service frequency, unit count or work area, access window, and the conditions that apply."],
    ],
  },
  {
    slug: "longview-tx",
    name: "Longview",
    image: "/images/jobs/tx-14.jpg",
    description: "Mobile fleet and pressure washing in Longview, TX for commercial property, trucks, equipment, concrete, and homes. Request a free written quote.",
    lead: "Longview quote requests can range from a few work trucks to a storefront, equipment yard, driveway, or recurring commercial schedule. Lone Star Total Wash brings the wash to the approved site and plans the work around access and operating hours.",
    planning: "For a useful Longview estimate, send the location, unit count or approximate square footage, photos of the normal buildup, and the hours the site is available. That gives Travis enough detail to separate a quick quote from a job that needs a walk-through.",
    focus: "Commercial sites, working fleets, and property exteriors",
    audiences: ["Fleet yards, delivery vehicles, semis, buses, and service trucks", "Storefront entrances, sidewalks, parking areas, and dumpster pads", "Construction and heavy equipment at approved yards or job sites", "Driveways, patios, walkways, brick, and home exteriors"],
    faq: [
      ["Can commercial washing in Longview be scheduled after hours?", "After-hours and weekend scheduling may be available when the site, lighting, access, noise, drainage, and reopening time allow it. The estimate confirms the operating window."],
      ["Can you quote multiple Longview fleet units together?", "Yes. Send the number and type of units, where they park, and when they are normally back at the yard. Published base prices provide a starting point."],
      ["Do you provide one-time and recurring service in Longview?", "Both can be quoted. Recurring work requires a written service agreement and an approved weekly, monthly, quarterly, or seasonal schedule."],
    ],
  },
  {
    slug: "marshall-tx",
    name: "Marshall",
    image: "/images/jobs/tx-21.jpg",
    description: "Marshall, TX mobile fleet and pressure washing for trucks, equipment, storefronts, concrete, and residential property. See pricing and request a quote.",
    lead: "Lone Star Total Wash reviews Marshall jobs for mobile fleet washing, heavy-equipment cleanup, commercial exterior work, and residential pressure washing. Customers see real completed work and published base rates before asking for a quote.",
    planning: "A Marshall quote should identify what is being washed, where it will be parked or staged, and the best service window. For property work, include the surfaces, approximate size, access points, water, drainage, and anything that must stay open during the job.",
    focus: "Truck, equipment, commercial, and residential washing",
    audiences: ["Semis, trailers, tankers, vans, and company vehicles", "Heavy machinery and contractor equipment", "Commercial entries, flat work, brick, and exterior surfaces", "Residential concrete, patios, walks, porches, and exteriors"],
    faq: [
      ["Does Lone Star Total Wash travel to Marshall?", "Marshall is listed in the East Texas service area. Send the exact address and scope so Travis can confirm the current route, travel, and scheduling options."],
      ["What should I send for a Marshall equipment-washing quote?", "Include the machine type, quantity, job or yard location, photos of the buildup, access conditions, and the preferred day or service window."],
      ["Are Marshall quotes free?", "Yes. Quote requests are free and carry no obligation. Final pricing depends on the written scope and the actual site or equipment conditions."],
    ],
  },
  {
    slug: "kilgore-tx",
    name: "Kilgore",
    image: "/images/jobs/tx-30.jpg",
    description: "Kilgore mobile fleet, heavy-equipment, commercial, and residential pressure washing. Review real East Texas work and request a free quote.",
    lead: "Kilgore contractors, fleet operators, property managers, and homeowners can request mobile washing without sending equipment across town. Lone Star Total Wash reviews the site and work window before confirming the written scope.",
    planning: "Equipment and work fleets need more than a generic per-hour promise. Send the unit mix, parking or staging plan, normal buildup, sensitive areas, access, and the time the equipment is actually available. Property quotes should include photos and approximate measurements when possible.",
    focus: "Heavy equipment, fleet yards, and exterior property work",
    audiences: ["Excavators, skid steers, dump trucks, and contractor machinery", "Service fleets, pickups, trailers, and commercial vehicles", "Parking areas, sidewalks, building exteriors, and work zones", "Residential drives, patios, brick, and outdoor surfaces"],
    faq: [
      ["Can heavy equipment be washed at a Kilgore job site?", "Sometimes. The site must have safe access and an approved work area. The quote reviews drainage, utilities, operating traffic, and equipment placement before a date is accepted."],
      ["How is heavy-equipment washing priced?", "The website publishes an hourly base rate. The final estimate confirms machine size, buildup, access, travel, water, and site-specific requirements."],
      ["Can a Kilgore fleet set a recurring schedule?", "Yes, when the route and operating window fit. Send the unit count, return-to-yard timing, and desired frequency so the schedule can be reviewed."],
    ],
  },
  {
    slug: "tyler-tx",
    name: "Tyler",
    image: "/images/jobs/tx-18.jpg",
    description: "Tyler, TX mobile fleet and pressure washing for approved commercial, equipment, concrete, and residential jobs. Send the location for a free quote.",
    lead: "Tyler jobs are reviewed by location, scope, route, and schedule before a service date is accepted. That protects the customer from a vague estimate and gives Travis the information needed to say exactly what can be handled.",
    planning: "Start with the Tyler address, photos, equipment count or approximate work area, and preferred timing. Because this is a mobile service based in Hallsville, the quote confirms travel and site logistics along with the washing scope.",
    focus: "Route-confirmed mobile washing with a written scope",
    audiences: ["Commercial vehicles and multi-unit fleet requests", "Storefronts, sidewalks, concrete, and exterior work areas", "Heavy equipment at accessible yards or approved sites", "Driveways, patios, walkways, brick, and home exteriors"],
    faq: [
      ["Does Lone Star Total Wash serve every Tyler address?", "Tyler is in the listed service area, but each request is reviewed for the exact location, route, job size, and schedule before service is confirmed."],
      ["What makes a Tyler quote faster?", "Send clear photos, the address, approximate square footage or unit count, surface or equipment type, and the days or hours the site is available."],
      ["Is there an obligation after requesting a Tyler quote?", "No. The quote request is free. You can review the written scope, price, and proposed schedule before deciding whether to book."],
    ],
  },
];

export const fleetPrices = [
  ["Semis", "$38.50"],
  ["Trailers", "$44"],
  ["Two-axle dump trucks", "$55"],
  ["Cement trucks", "$55"],
  ["Three-axle dump trucks", "$65"],
  ["Garbage trucks", "$70"],
  ["Trailer washouts (reefer / dry box)", "$32"],
  ["Straight truck washouts", "$21"],
  ["Box trucks (up to 16 ft)", "$25"],
  ["Box trucks (16–26 ft)", "$45"],
  ["Step vans", "$25"],
  ["Service trucks and pickups", "$20"],
  ["Sprinter / delivery vans", "$20"],
  ["Passenger / tour bus", "$50"],
  ["School / shuttle bus (up to 30 ft)", "$35"],
  ["School / shuttle bus (over 30 ft)", "$40"],
  ["Cargo trailers (under 16 ft)", "$17"],
  ["Cargo trailers (16–25 ft)", "$24"],
  ["Cargo trailers (over 25 ft)", "$30"],
  ["Aluminum tankers — wash only", "$44"],
  ["Aluminum tankers — with brightener", "$100"],
  ["Heavy equipment (any size)", "$137.50 / hour"],
];

export const jobs = [
  ["tx-27.jpg", "Mack day cab and belly dump trailer", "fleet"],
  ["tx-21.jpg", "Semi truck before and after", "fleet"],
  ["tx-26.jpg", "Mack day cab before and after", "fleet"],
  ["tx-28.jpg", "Fleet truck before and after", "fleet"],
  ["tx-29.jpg", "Tanker truck before and after", "fleet"],
  ["tx-23.jpg", "CAT skid steer before and after", "equipment"],
  ["tx-30.jpg", "John Deere 210 excavator", "equipment"],
  ["tx-25.jpg", "Excavator boom and bucket", "equipment"],
  ["tx-24.jpg", "Equipment hydraulics washed clean", "equipment"],
  ["tx-2.jpg", "Storefront entrance before and after", "property"],
  ["tx-14.jpg", "Office storefront and walkway", "property"],
  ["tx-10.jpg", "Commercial walkway", "property"],
  ["tx-15.jpg", "Sidewalk and parking stalls", "property"],
  ["tx-17.jpg", "Storefront sidewalk", "property"],
  ["tx-3.jpg", "Sidewalk before and after", "property"],
  ["tx-4.jpg", "Brick building and patio", "property"],
  ["tx-5.jpg", "Brick wall washed clean", "property"],
  ["tx-6.jpg", "Brick building exterior", "property"],
  ["tx-7.jpg", "Brick building corner", "property"],
  ["tx-8.jpg", "Brick building and entry", "property"],
  ["tx-9.jpg", "Back porch step", "residential"],
  ["tx-11.jpg", "Entry steps", "residential"],
  ["tx-20.jpg", "Walkway at brick building", "property"],
  ["tx-18.jpg", "Residential driveway", "residential"],
  ["tx-19.jpg", "Carport and driveway", "residential"],
  ["tx-12.jpg", "Concrete wall mid-wash", "property"],
  ["tx-22.jpg", "Brick mailbox restoration", "residential"],
];

export const guides = [
  {
    slug: "how-often-should-a-commercial-fleet-be-washed",
    title: "How Often Should an East Texas Commercial Fleet Be Washed?",
    description: "A practical way to choose weekly, monthly, quarterly, or seasonal fleet washing based on routes, buildup, inspections, and presentation.",
    read: "5 min read",
  },
  {
    slug: "commercial-pressure-washing-quote-checklist",
    title: "Commercial Pressure Washing Quote Checklist",
    description: "The measurements, access details, photos, and scheduling facts that make a property-washing quote faster and more accurate.",
    read: "4 min read",
  },
  {
    slug: "prepare-property-for-pressure-washing",
    title: "How to Prepare a Property for Pressure Washing",
    description: "A simple pre-service checklist for gates, vehicles, outlets, pets, customers, signage, and exterior items.",
    read: "4 min read",
  },
];
